### ISSUE TITLE
Index Set notation

### ISSUE THREAD

**Issue by srush** [namedtensor/notation#10]
To summarize an idea from Boaz. 

There would be a mirrored index set that only allows you to index into a specific name. The use case would be: 

\sum_{i \in width} A_i  

Here the unnamed index is non ambiguous since the index sets are guaranteed to be disjoint. Currently do this with the point-free style: 

\sum_{width} A

An alternative would be to use our index notation 

\sum_{i \in [w] } A_{width=w} 

I don't mind the last notation, but it does require repeating the size. 

This also relates to the previous question that people found reductions a bit strange when used with \sum. I actually find that argument relatively compelling in the broadcasted case 

\sum_{width} [ A + B ] 

vs. 

\sum_{i \in width} [ A_i + B ]  or \sum_{i \in [w]} [ A_{width=i} + B ] 

Could be a bit more clear? For some reason my brain wants to name the sum index and have it act first as opposed to broadcasting and then reducing. Perhaps the case is nicer if there are multiple uses of the index. 

\sum_{i \in width} [ A_i + B * C_i ]

**Comment by srush** [comment]
On a downside, this does break things like the max pooling example. There are two `height` names of different sizes, and the indices really do cross over between names. 

![image](https://user-images.githubusercontent.com/35882/101093579-ffe5b280-3588-11eb-93cd-8ca5ed2ba1bf.png)

I guess though we could just say these are indexing the name set whereas the other notation is bound to the name label. Also I should change this to height'

**Comment by davidweichiang** [comment]
My understanding of the idea was not that width should be tied to a size, but that you could write something like

\sum_{i \in width[32]} A_i

and that i ranges from width:1 to width:32, that is, it ranges over integers that have been tagged as 'width'.

Cons:
- It wouldn't work for summing over two indices with different names
- It requires you to choose a variable

**Comment by srush** [comment]
I think my understanding was the same? I don't understand the cons though, can't you stack them since they are orthogonally typed:

\sum_{i \in width[32], j \in height[32]} A_{i,j} ?  or \sum_{i \in width[32], j \in height[32]} A_i B_j ? 

I guess the nice part of only having one name per function is that you wouldn't have to rewrite the [32] part. 

(I'm not convinced this is critical. It seems like standard indexing `width=i` can do this, just a bit verbose.)

**Comment by davidweichiang** [comment]
If we have two tensors A and B and both have indices height and width with size 32, and we want to multiply them like matrices, we can do

\sum_{i=1}^100 A_{width:i} B_{height:i}

which I don't think the proposed notation can help with. TBF, our current \ndot doesn't help either.

**Comment by davidweichiang** [comment]
In https://hackmd.io/@boazbk/S1YvQpwoD @boazbk gives a couple more examples. He also proposes that if name 'width' is only ever used with a single size (say, 32), then we can equate 'width' with the set {width:1, ..., width:32}.

I am okay with the idea of defining width[32] = {width:1, ..., width:32} and using that in summations. The discussion in #2 is heading in that direction, and @boazbk's new examples give some more reasons why this might be helpful.

But I'm not a fan in general of "global" rules like a rule that would let you write 'width' instead of 'width[32]'. What if I'm writing a paper section and my co-author adds a section that uses a tensor with a different width? Then my section is broken.

**Comment by boazbk** [comment]
I think that for clarity in a paper, it is sometimes better not to carry around this [32], especially if this is a hyper-parameter that can be changed later.

For example, if you use three different widths in the paper, maybe you just call them width_1, width_2, width_3. This way, if the paper is a generic architecture that could be instantiated in different ways (for example maybe you can networks of different widths) then most of the paper does not depend on "hardwired constants" such as 32. You just want to make sure that operations align with each other.

Moreover, if a tensor A has only a single dimension with the width name (for example, it is a width_1 by height_1 matrix) then sum_{width} A  would be well-defined. Only when you try to contract two vectors together, you need to make sure that their dimensions match up. So you can only write something like 

sum_{w in width} A_w ⋅ B_w

if A and B have the same width dimension. And if they both have (for example) a width_1 and width_2 dimensions, then you can write 

sum_{w in width_1} A_w ⋅ B_w

Another advantage of thinking of general annotation rather than numbers is that sometimes maybe dimensions "accidentally" have the same numbers. For example, maybe your second layer happens to have the same number of neurons as the first layer, but this is not really a "law of nature" and so you would rather think of the operator corresponding to the second layer as taking a tensor that has a hidden_1 dimension and outputting a vector that has a hidden_2 dimension.

In fact, if you repeat several identical blocks, you might describe it as an operator that takes a vector of shape (hidden_i) and outputs a vector of shape (hidden_{i+1})

**Comment by boazbk** [comment]
P.s. As I mentioned, I think that annotation might not always be numeric. For example, you might have channel_RGB, channel_gray and channel_64 for channels that correspond to RGB images, channels that correspond to a gray scale image (even if it ends up being dimension 1) and channels that don't really have such a meaning and are simply 64 different numbers.

**Comment by davidweichiang** [comment]
If someone wants to be able to write \sum_{w \in width} A_w, they can simply define width' = width[32] and then write \sum_{w \in width'} A_w. If someone really doesn't want to make a new symbol, they can write, "Throughout this paper, we write width for width[32]." Doesn't that have the same effect, using the existing machinery?

**Comment by davidweichiang** [comment]
Closing this, since the mega-discussion in #2 seems to cover this.
