### ISSUE TITLE
Expanded examples

### ISSUE THREAD

**Issue by davidweichiang** [namedtensor/notation#20]
In #6, it was suggested to take the belief propagation example and merge it with the example on Bayes' rule, to form an expanded example on using named indices for random variables.

**Comment by davidweichiang** [comment]
@ctongfei would your BP example work just as well with a locally normalized model? That might help it to fit better with the Bayes rule example.

**Comment by davidweichiang** [comment]
Should we just merge the Transformer and LeNet examples into the main document? Or @srush do you like having them separate?

**Comment by srush** [comment]
Sure! Maybe put them at the end? I just thought they were a little long. 

LeNet is dependent on  https://github.com/namedtensor/notation/issues/12 . In particular it needs some reshape from A_{height, width, channel} to B_{features} . If you are okay with just leaving the bijection unspecified it is fine. (As far as I know that is the only use case for https://github.com/namedtensor/notation/issues/12 . Other forms of splitting I am happy doing with explicit indices.)

**Comment by davidweichiang** [comment]
I think the pieces of the transformer except position encodings are in there already, so it would not add too much.

Same for the LeNet example...BTW, we could avoid reshaping by making the weight matrix W^1 have four indices (height, width, channels, and hidden). Maybe it would be good to show both options.

**Comment by srush** [comment]
Hmm. in theory I like the four index approach. But bunching has a nice abstraction in that you can send it off to a standard function expecting 1 named dim.

**Comment by davidweichiang** [comment]
Yeah, that's why I thought it might be interesting to compare both approaches.

Thinking about how different components glue together is instructive; for example, looking at the Transformer example, I see that layer norm is defined differently in the main document and the Transformer document, and gluing them together is a little puzzle. (The easy way out would be to drop instance norm and just define batch and layer norm.)

**Comment by srush** [comment]
* We can do both if you want? If we are going to show off grouped renaming though, I think this is the canonical case to use. People are going to ask about it, so we might as well highlight it here. 

* I blame computer vision for being sloppy. We can just do batch norm as batch and layer norm as features. That seems to make the point clear about the naming.

**Comment by ctongfei** [comment]
> @ctongfei would your BP example work just as well with a locally normalized model? That might help it to fit better with the Bayes rule example.

@davidweichiang I'm not sure what "locally normalized model" mean here?

**Comment by davidweichiang** [comment]
Sorry, I mean a Bayesian network or directed graphical model.

**Comment by ctongfei** [comment]
I don't see how it does not work -- after all, factor graphs are more expressive than Bayesian nets?

**Comment by davidweichiang** [comment]
Great -- if you think it would be a useful addition to the example on discrete random variables, would you like to add it?

**Comment by davidweichiang** [comment]
@srush in your examples, you often define a function with parameters like FFN(X;W,b) and then call it without arguments, like FFN(X). It's easy to understand that a W and b should be created implicitly, but it's less easy to understand, if FFN is called twice, whether they should have the same or different parameters. In code we create an object or a closure but in writing I'm not sure how to express this.

**Comment by srush** [comment]
Good point. I will make it more explicit (I did that in the cnn example)

**Comment by davidweichiang** [comment]
OK, but I'm wondering if there's a way to do it without having to number the parameter variables...that would be super useful in general.

**Comment by davidweichiang** [comment]
Oh, maybe use index name sets to distinguish them —

FFN_in,out(X; W, b)

where in and out are named _index sets_ (not just names). If W and b are omitted, defaults are created. If FFN is called again with the same names, the same W and b are used.

More verbose than code but a lot less verbose than explicit declaration of W’s and b’s. This will cut down on renaming too.

**Comment by davidweichiang** [comment]
Example: if we define a fully-connected layer as:

<img width="279" alt="image" src="https://user-images.githubusercontent.com/1399913/101920225-8d349280-3b99-11eb-805f-767467e8404d.png">

where in and out are named index sets (PR #21), then the last layer of the LeNet example is:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/1399913/101914411-48f1c400-3b92-11eb-84a1-df168a3eaee8.png">

where layer, hidden, and class are named index sets.

**Comment by davidweichiang** [comment]
I am trying a reorganization of the examples section that also makes use of the idea above.

@srush Your conv1d doesn't have a bias, and your conv2d doesn't have output channels. Could you confirm that to make this uniform, both should have biases and output channels?

**Comment by srush** [comment]
Everything should have biases. Output channel (channel') was broadcasted. We can make it explicit.

**Comment by srush** [comment]
In our stylesheet should we recommend that people use long types? I agree it is helpful to have the types be documentation in additional to their minimal need.

**Comment by davidweichiang** [comment]
Ah, I see (about channel'). I am pondering whether the trick shown above will work for convolution too, but it seems like it would require an unreasonable number of subscripts...same for layernorm.

**Comment by davidweichiang** [comment]
Also can you confirm: the 2D bias should not have width and height? And the 1D should not have seq?

**Comment by srush** [comment]
I can confirm that bias is just out_channels size => `self.bias = Parameter(torch.Tensor(out_channels))`  (Same parameters can be used for different length sentences.)

I don't think I like the above notation. I'm not sure I understand how the indexes convey that there are different parameters?

**Comment by davidweichiang** [comment]
> I don't think I like the above notation. I'm not sure I understand how the indexes convey that there are different parameters?

OK because it wasn't working very well for the other kinds of layers! But I still hope for a way to avoid numbering all the parameters.

**Comment by srush** [comment]
Yup. Up for other ideas! I agree numbers are bad, but this problem may be outside the scope of named dimensions.

**Comment by boazbk** [comment]
Haven't yet looked at the examples, but biases in general are a pain. It might be nice to just have an operation that takes an input tensor, and adds the constant tensor $1$ in the 0-th coordinate of all its axes. So then if the weight has a 0 coordinate too, we just take a dot product.

**Comment by davidweichiang** [comment]
This implicit-parameters problem is really serious though...for example, the line in the Transformer that currently reads

<img width="252" alt="image" src="https://user-images.githubusercontent.com/1399913/101986072-b87eb680-3c59-11eb-906f-7a66e15e9d35.png">

would have to become _much_ more verbose:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/1399913/101986122-009dd900-3c5a-11eb-9fa2-8d0d756636f9.png">

My previous idea was to hijack index-names to solve this problem: Give each layer of the network a different name, as is done in the MLP example (input, hidden, output), which causes the parameter tensors at each layer to have a different shape (input x hidden, hidden x output). Adopt the convention that if implicit parameters have the same shape, they are the same parameter; otherwise, they can't be. The trouble was that the subscripts piled up way too much.

Other ideas would indeed be outside the scope of named dimensions. For example,

<img width="278" alt="image" src="https://user-images.githubusercontent.com/1399913/101986518-3b087580-3c5c-11eb-8d64-2b4c7906fc36.png">

where MHA and lnorm are somehow defined so that the superscript is used to select the parameter tensors that have that same superscript.

**Comment by ekshaks** [comment]
Will defining an a parameter array `W = [W^Q, ..., W^O]` and using `W` as a single argument to `MHA` help?

**Comment by davidweichiang** [comment]
That's kind of what @srush did do for one of the examples. But it will still be quite verbose. I'm leaning towards the superscript idea. I think it can be explained pretty briefly and (hopefully) won't feel like "yet another piece of notation".

**Comment by boazbk** [comment]
I defined tensors as partial functions defined on a product set but maybe
we don’t need this restriction and then we can have an axis named **part**
defined over the set  { “Q”,”K”,.. }

We can say that by default tensors are defined on a product set but they
can also not be, and operations such as + and dot product can take two
tensors of the same support even if this support is not a product set

**Comment by srush** [comment]
So I think this is outside the scope of the proposal, but... 

I view parameters as existing in a global "reader monad". It's fully functional but not passed directly at each call. Each function can just get its parameters but asking for them by their ids. (That is how people implement them these days in languages like Jax, and debatably pytorch.)

Under that view, I like @davidweichiang 's proposal . As long as there is some identifier like this it seems fine => 

<img width="278" alt="image" src="https://user-images.githubusercontent.com/1399913/101986518-3b087580-3c5c-11eb-8d64-2b4c7906fc36.png">

But the caveat is that when you do that you need to declare the size for that instance somewhere. I'm okay with it being global, for transformers (since everything is the same size). But for LeNet each superscript will have different sizes, so that needs notation.

**Comment by boazbk** [comment]
Much of the pain with sizes would disappear if instead of thinking of a tensor A as being defined (for example) on width[..32] , height[..32] we would conceptually think of it as being defined on the full axes width, height (i.e. on all natural numbers) but where A_{width[i],width[j]}=0 whenever either i>32 or j>32

Are there natural examples  where this would be a problem?

**Comment by davidweichiang** [comment]
@srush Yeah, for the convnet one would need to write the sizes of all the layer parameters, but still be able to avoid having to include the parameters in the function calls.

What are opinions in general about whether the layers of a network should use different axis names or all reuse the same axis name? The former still seems to me like the most concise way to state different sizes for different layers.

**Comment by srush** [comment]
My intuition is that it should be the same name? To me it's the same function that is polymorphic in the args size (or copied as you said). However, if you think there is a nice way to make it concise, happy to consider it. For transformer would you number the axes?

**Comment by davidweichiang** [comment]
Yeah, let's make them all the same name.

I think writing the sizes in the convnet example wouldn't be so bad. If there were more layers, you could compact it like

<img width="549" alt="image" src="https://user-images.githubusercontent.com/1399913/102030459-de52ab00-3d80-11eb-9cf6-e8069abf80b7.png">

and then give values for the c_l, kh_l, and kw_l.

The superscript idea does still simplify the model equations:

<img width="368" alt="image" src="https://user-images.githubusercontent.com/1399913/102030506-06daa500-3d81-11eb-86f7-8cdae5c0d385.png">

**Comment by srush** [comment]
This seems nice to me. I think networks that change shapes each layer are complicated, and so they should require a bit more work to specify. 

One minor thing. "Layer" is a bit of an arbitrary concept. Is the idea here that W^3 knows the layer it is mapping to? I feel like maybe we should only have conv2d^1 and conv2d^2, and then state the mapping? Alternatively we could have better names for the X^1 .. .X^4.

**Comment by davidweichiang** [comment]
The definition of conv2d^l would depend on W^l and b^l, like this:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/1399913/102032149-0a245f80-3d86-11eb-95e6-9812e7e44f94.png">

There wouldn't be any dependence on a concept of layer -- or maybe I don't  understand the question?

**Comment by srush** [comment]
Hmm, how about we leave conv2d the same, but write the closure like this? (it's only one more line). 

conv2d^l = conv2d(\cdot ;  W^l, b^l) where 
W^1 \in ...
W^2 \in ... 

I just think of conv2d as a general function, the superscript as something model specific.

**Comment by davidweichiang** [comment]
That works too. There would be an extra line for each function that has parameters, though.

**Comment by srush** [comment]
If that becomes an issue, I think you can get around it by modularity? For transformers, you could have a ResidualMultiHead function that takes both the MHA and layernorm params. Just wrap the biggest repeating block. For non-repeating blocks, I think you can just name the weights and pass them in. (the problem was numbered weights right?)

For transformer I am also fine with having the constant sizes e.g. `d_model` in the `MultiHead` function definition, and not giving explicit types to the params, e.g. just writing `MHA^l = MHA(\cdot; W^l_q, W^l_h, ... )` since the function only takes fix sized parameters. (But you still need superscripts to indicate different layers.)

**Comment by boazbk** [comment]
I still don't understand why we need a different axe for each layer, and also variables for the various sizes of the axes.
Convolution can be a general function that takes the input, weights, and biases, and reads off from the weight vector all the information that it needs.


How about something like the following? 

(This is very rough but hope you get the idea, I am using here the notation that one can define a tensor A over ax^1, ax^2 by writing [ a(i,j) ]_{i in ax^1, j in ax^2} where a(i,j) is the value of A at the i,j -th coordinate ):

![image](https://user-images.githubusercontent.com/5474168/102036944-0ac2f300-3d92-11eb-9aab-eb4fcab838a6.png)

**Comment by srush** [comment]
Forgetting about the top part of this for now where there are still disagreements.  The bottom is actually pretty clean and doesn't need closures.

David if we do it like: 

X^l = BLOCK(X^l-1, \ell^l_x, \ell^l_y ; W^l, B^l) for l = 1 .. d

Are the numbered W^1 and \ell^1's okay with you?

Boaz, even in your notation we still need to give the explicit sizes for W^1 ... W^d . How would you do that? Would you type them W \in channel'[20] x channel[10] or would you just say |channel(W^i)| = 10 . What about the biases? Maybe you could finish that last paragraph?

**Comment by davidweichiang** [comment]
Although I said initially that numbering the parameters was what I was trying to avoid, it seems really hard to avoid that — all of the solutions proposed so far have some kind of numbering. But we can still hopefully avoid a lot of repetition and clutter.

@srush I understood later that your 

> conv2d^l = conv2d(\cdot ; W^l, b^l) 

is equivalent to constructing a Conv2d object. That makes sense and I think we should do it that way. 

Defining a “block” function is fine, but for the Transformer it would have a lot of parameters (12, if I’m not mistaken). I do think we need some equivalent of closures.

**Comment by boazbk** [comment]
Here is (again very rough and incorrect but hopefully you get the picture) attempt of how the block function for a transformer would look like. I think the main parts a reader wants from a description of the model is a way to remember for each intermediate value, what type it is, in the sense of what axes does it have. (It doesn't matter much the sizes.)

![image](https://user-images.githubusercontent.com/5474168/102091090-52766880-3dec-11eb-953b-c7cf5850debd.png)

**Comment by davidweichiang** [comment]
Each block should have:

- self-attention: W^Q, W^V, W^H, W^O
- feedforward neural networks: W^1 and b^1 for the first layer, W^2 and b^2 for the second layer
- layer normalization: \beta^SA and \gamma^SA after self-attention and \beta^FF and \gamma^FF after the FFNN.

**Comment by davidweichiang** [comment]
Here's what it looks like using @srush's way of making modules:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/1399913/102092432-13e1ad80-3dee-11eb-8a38-55a7074156d2.png">

Layer norm:

<img width="216" alt="image" src="https://user-images.githubusercontent.com/1399913/102092478-1d6b1580-3dee-11eb-81d5-3d0343fc23fb.png">

- where xnorm is a generic normalization layer I defined elsewhere
- there's only one possible definition for \beta^l and \gamma^l, so they are left implicit

FFNNs

<img width="250" alt="image" src="https://user-images.githubusercontent.com/1399913/102092533-2c51c800-3dee-11eb-8e47-86034ae069fc.png">

- hope it's clear that Y and Z are local; not sure what's the best way to split a function definition into multiple steps.
- Y has a different size; this was the most concise way I could think of to indicate this.
- then the sizes of W and b can be inferred.

The self-attention parameters:

<img width="184" alt="image" src="https://user-images.githubusercontent.com/1399913/102092691-54412b80-3dee-11eb-94c6-529a9bc0468d.png">

Self-attention equations
<img width="317" alt="image" src="https://user-images.githubusercontent.com/1399913/102092924-923e4f80-3dee-11eb-9ee0-ceae22735a8c.png">

<img width="239" alt="image" src="https://user-images.githubusercontent.com/1399913/102092946-99655d80-3dee-11eb-9883-4cc7352623ab.png">

**Comment by boazbk** [comment]
This generally looks very good to me! The thing that I would add is annotations as to the types of the intermediate values T^i, X^i, since I think that can help clarify what's going on. 

I would prefer if rather than using notation such as "Func^i(....)" one uses notation such as Func_{theta^i)(....) 
This would indicate that Func^1, Func^2 , etc... are really all the same function just given as input a different set of weight tensors, and we use theta^i to be the collection of weights that are used for the function Func^i 
(also i does not have to be just a number and can be a more meaningful way to specify the parameters)

So we can have an overall collection { theta^i  } of parameters, where each \theta^i is itself a collection of tensors, and we use the notation F_{theta^i}(X) to say that we apply F on the tensor X and all the tensors in the collection theta^i

It's perfectly fine if a function cannot be written as just a one line equation and one needs to describe the relation between input and output in pseudocode involving several steps. So I see no issue with using the intermediate value Y in the definition of the FFN.

I like it that sizes are disappearing from superscripts  :) I hope that we can also drop the size from the Y  - it can be inferred from the weights.

Generally an advantage of stating the signatures of components in generic terms, and not talk about sizes, is that it makes it easy to swap out parts. For example, maybe in a future version instead of the current net in the FFN one would use a different one with more layers, or another architecture. The point is that what we really care about the FFN to plug it into the general consrtructoin is the type of tensor it takes as input and type it produces as output, and not really anything else.

**Comment by davidweichiang** [comment]
The superscript l's can definitely be non-numeric -- you can see in the example I gave that it's sometimes 1', 2', etc.

Currently I'm inferring the sizes of the FFNN weight matrices from the size of Y. We could go in the other direction, inferring the size of Y from the sizes of the weight matrices, but that would mean writing d_ff in three places instead of one:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/1399913/102105271-362ef780-3dfd-11eb-8ce4-a601844da53d.png">

In both versions, I'm also bending the rules by sometimes writing 'layer' with a size d_ff and sometimes without a size (to mean layer[d_model]). That's not nice and I haven't figured out a solution yet.

**Comment by boazbk** [comment]
I again advocate dropping sizes, so that this is not "bending the rules" but rather follows from the rule. Then you can also drop d_{ff} from the equation. (A good sign that you can drop a variable is if you never actually use it)

I would write this as follows. This is not just about removing clutter but also about reminding the reader what parts have which types.
The following makes it clear that FFN is a function that, based on some parameters, maps a { **layer** } type tensor into a { **layer** } type tensor. Whether or not the input and output have the same size is an accidental feature, and could depend on the particular parameters. It also makes it clear that it does so by mapping X first to an intermediate value Y, which could have the type { **layer'** } though I think { **hidden** } is more informative. 

When we write the description of FFN we don't need to keep track of the superscript ell - after all FFN is a generic block that can take any tuple of parameters for the weights and biases, and its description should not depend on the fact that it happens to be component in a transformer.


![image](https://user-images.githubusercontent.com/5474168/102110992-da1ba180-3e03-11eb-9fae-6639bce3a1cf.png)

**Comment by davidweichiang** [comment]
If you give the hidden layer a different name, then the problems I mentioned go away -- I was just hoping to use a function Full for the fully-connected layers, and Full has axis names hardcoded into it.

**Comment by boazbk** [comment]
> If you give the hidden layer a different name, then the problems I mentioned go away 

I think the problem just goes away if it happens to be the case that the layer axis for the input of FFN has the same size as the layer axis of FFN. This is just an accidental choice for the current architecture, but may change, and so shouldn't make a huge difference if we want to express an architecture where this is not the case.

If you want, you can have a function FULL (note that the natural way to state it is as outputting a single number, it can then be expanded automatically using dangling axes):

![image](https://user-images.githubusercontent.com/5474168/102126511-29b89800-3e19-11eb-9598-bd06a9d7b25a.png)

**Comment by davidweichiang** [comment]
I think the contraction inside the second FULL should be along axis hidden, not layer.

To make this work, one would have to parameterize FULL by the name of the input axis (like we do for \sum). That might not be too bad if we use the "output a scalar" trick:

<img width="232" alt="image" src="https://user-images.githubusercontent.com/1399913/102129297-1f000200-3e1d-11eb-9a5d-a5810829ed1b.png">

<img width="449" alt="image" src="https://user-images.githubusercontent.com/1399913/102128706-41dde680-3e1c-11eb-8c92-f0c1cb0759f2.png">

**Comment by boazbk** [comment]
Yes that's very elegant!

**Comment by boazbk** [comment]
My variant of this would be the following:

![image](https://user-images.githubusercontent.com/5474168/102137471-e5cd8f00-3e28-11eb-97a2-d30e7b4d783f.png)

**Comment by srush** [comment]
@davidweichiang  I'm 95% with you on the notation. Couple small aestetic things: 

* I prefer the version where you fully type the W trained parameters. I know they can be implied but I think it is confusing to the reader since it is often necessary to count them. For instance in this model they make up the bulk of what is trained. 

* maybe 1a and 1b instead of ' s . Double superscripts gets messy quickly. 

* Let's standardize font on functions. Maybe also aim to keep them lowercase? 

* Since everything in our world is a tensor. Should they all be upper case? When is it okay to use lower case?

**Comment by davidweichiang** [comment]
@srush there are a bunch of variations above; which one are you voting for? Or just not the one where W and b were inferred from Y?

Instead of 1’ or 1a would it be okay to make all the odd numbers self-attention and all the even numbers feedforward?

For function names, I like lowercase roman but that can make word segmentation difficult. And underscores and hyphens would look terrible. Maybe \, between words?

The document claims that tensors are always uppercase but it’s not true; we do use lowercase letters for order-one tensors. I don’t have a strong opinion about this.

**Comment by srush** [comment]
Let see.

- As long as W is always declared in the outermost closure function I am okay with any variants. (Bias I would be fine leaving out.)

- I think hidden should be the axis name of `Full`. I think names should be words and never higher-order. 

- I don't love camel case or abbreviation names.  The , strategy seems nice 

- I like the idea that rank 1 tensors can be lower case and rank 0 can be greek letters. People have that intuition, it should not change because of batches.

- I would prefer that a  "layer" always be the minimal repeating unit. If there is a sublayer why not l,1 in the superscript? I don't like when the number changes because of a line break.

**Comment by davidweichiang** [comment]
My comment didn't render correctly; I had suggested `\,` (a small space) between words, which is used in operators like "lim sup" and "arg max". I tried it and didn't like it.

<img width="385" alt="image" src="https://user-images.githubusercontent.com/1399913/102155609-e6c2e880-3e49-11eb-9408-a580ab1a08cb.png">

**Comment by srush** [comment]
Okay, so PascalCase everywhere?

**Comment by davidweichiang** [comment]
These functions should be lowercase, right: exp, tanh, min, max?

Would it be reasonable for functions that have learnable parameters to be in PascalCase and functions that don't to be in lowercase? So: mean, var, softmax, maxpool, but LayerNorm, SelfAttention, Conv2d?

The above PR does not yet incorporate all of the discussion above, but is at least (afaict) an unambiguous formulation of the Transformer and LeNet examples.

**Comment by srush** [comment]
That sounds good. Maybe only the ones that hide/contain their params? So if you wanted a conv2d that took an explicit kernel it would be lower case.

**Comment by boazbk** [comment]
One comment is that dangling axes could potentially be more than just batches (for example multiple heads) and so a variable could be a scalar or a one dimensional tensor in one context, and a higher dimensional tensor in another. So maybe we just say that upper case, lower case, and Greek letters are all fair game as identifiers for tensors, but we recommend that one uses Greek letters for tensors of smaller order than lower case, and lower case for tensors of lower order than upper case.

**Comment by davidweichiang** [comment]
@srush If we wrote both Conv2d and conv2d that could work, but then we're faced again with the problem of lowercase words running together (maskedmultiheadselfattention). Also, wouldn't it kind of feel opposite of Python if "instantiation" looked like

Conv2d^l(X) = conv2d(X; W^l, b^l) ?

I'm hoping it's the case that functions that have learnable parameters are basically little neural networks and so are more likely to have more complex names that need PascalCase, whereas functions that don't have learnable parameters are more likely to have simpler names and can be written in lowercase (as is traditional).

I'd be okay with this being something that we just do by example and not to make a recommendation.

For tensor names, is there a tradition of using Greek lowercase letters for scalars? I had never noticed.

**Comment by boazbk** [comment]
Actually the convention of writing functions with learnable parameters with upper case makes sense since at least sometimes (i.e., pytorch) their instantiation would be a class rather than a function. 

The convention can be that the learnable parameters can sometimes be dropped if they are clear from context. 

> For tensor names, is there a tradition of using Greek lowercase letters for scalars? I had never noticed.

I think it depends on the letter. Obviously  δ,ε are typically small positive numbers, and I think using α,β,γ  for scalars is also very common. However,  θ is often used for a collection of parameters that can contain several tensors, and μ is of course often used for a distribution.
