### ISSUE TITLE
Finding a 'middle ground' notation

### ISSUE THREAD

**Issue by ekshaks** [namedtensor/notation#23]
I’ve been reading through the different formulations and wanted to summarize my thoughts :

- My intuition aligns with the idea of axes as abstract types, but would like to avoid pre-/post-conditions unless necessary.
- so, suppose we define an axis \type{d} = (\name{d}, \size{d}), where \name{d} ‘uniquely identifies’ this abstract type \type{d}, and we try to work with \type{d} mainly and avoid explicit size.
- Now, it seems we need to create *variants* of \type{d}, depending on the program (or NN specification) context.
    - e.g. no two \type{d_i}, \type{d_j} participating in a shape can be *exactly* the same. so the notation must somehow distinguish between them, without forgetting that they are related.
    - an operation does a size change on the same conceptual axis  e.g. (\name{height}, h) -> (\name{height}, h’)
- So we may have two variants of \type{d}, one that changes the name only, and other that changes the size only. 
- To solve this, how about different annotations for each variant. i.e., write \type{d}’ if you only change size not name. \type{d}* if you change name, not size. (I chose prime and star as annotations arbitrarily)
    - so, in a shape with two similar axes, we write (\type{d}, \type{d}*) to distinguish them
    - for a transformation, we use \type{height} for input tensors and  \type{height}’ for output tensors, and specify how |\type{height}| and |\type{height'}| are related.
    - will it be sufficient to adopt this convention?

 It seems to me (and I may be generalizing wrongly) that several discussions are only about how to write down these two variants. What do you think? @davidweichiang @boazbk @srush 

My goal here is to neither make the notation too abstract (and say, lose size changes from function signatures), nor have explicit sizes floating around unnecessarily. Again, I hope I'm not going back in time on this topic.

**Comment by davidweichiang** [comment]
That seems pretty close to what we are converging on. I agree that an axis should be a (name, size) pair (or (name, set)) and therefore we need a way to change an axis's name and an axis's size.

- It seems like interest in a name-changing operation has been low, and people are pretty happy with just writing |foo|=|bar|. I'd be open to other ideas.

- The size-changing operation would be something like foo[newsize] where foo is an existing axis.

**Comment by boazbk** [comment]
I think the middle ground should be that it's possible to define both:

In some cases, the sizes are accidental, and an operation can really work on tensors of any size. In other cases, an operation really inherently is only defined for tensors of a particular size.

So, if you want to define a general transformation that operates on tensors of an abstract type independently of their sizes then you should be able to do so without writing the size.

If you want to define a function that explicitly only works on tensors of a particular size then you should be able to do this too.

For writing the restriction of the axis foo to the integers {1,...,size}, I prefer the notation foo[:size] or foo[..size] to foo[size] since the latter looks too similar to an indexing operation. For the former it's very clear what you mean, even if you haven't seen it before. 

So you can write an operation such as 

Func: R^{ax} --> R^{ax} 

or

Func: R^{ax[..128]} --> R^{ax[..64]}


I think there will always be need to express more complex relations, such as the case where the dimension of the output tensor depends dynamically on the content of the input tensor. So we will notation such as |ax(A)| to express the size of the axis ax in A.
